version: "3.8"

services:
    # image project
    app:
        container_name: controle9
        build:
            context: .
            dockerfile: Dockerfile
        image: especializati/laravel9-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - laravel-9

# nginx
    nginx:
        container_name: especializati-nginx
        image: nginx:latest
        restart: unless-stopped
        ports: 
            - "8989:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel-9
    
    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: telessaude
            MYSQL_ROOT_PASSWORD: root
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        networks: 
            - laravel-9

    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        ports:
            - 9000:80
        environment:
            - PMA_ARBITRARY=1
        networks: 
            - laravel-9
# queue
    queue:
        container_name: especializati-queue
        image: especializati/laravel9-app
        restart: always
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
            - app
        networks: 
            - laravel-9

# redis
    redis:
        container_name: especializati-redis
        image: redis:latest
        restart: unless-stopped
        networks: 
            - laravel-9

networks:
    laravel-9:
        driver: bridge
        ipam:
         config:
           - subnet: 10.5.0.0/16
             gateway: 10.5.0.1